defaults:
  - _self_
  - websocket_connection@smartsocket_connection: smartsocket_connection

connections:
  - name: smartsocket_connection
    connection: ${smartsocket_connection}


hydra:
  output_subdir: null
  run:
    dir: .
