services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser123
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./posgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: "pgadmin_container"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: testuser@gamil.com
      PGADMIN_DEFAULT_PASSWORD: testuser123
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadminfr
