version: "3"
services:
  kafka1:
    image: "bitnami/kafka:latest"
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_CFG_LISTENERS: 'INTERNAL://kafka1:29092,CONTROLLER://kafka1:2181,EXTERNAL://0.0.0.0:9092'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'INTERNAL://kafka1:29092,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka1:2181,2@kafka2:2181,3@kafka3:2181'

      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      BITNAMI_DEBUG: 'yes'
    volumes:
      - ./docker_data/kafka1:/bitnami/kafka
  kafka2:
    image: "bitnami/kafka:latest"
    container_name: kafka2
    ports:
      - 9093:9093
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_CFG_LISTENERS: 'INTERNAL://kafka2:29092,CONTROLLER://kafka2:2181,EXTERNAL://0.0.0.0:9093'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'INTERNAL://kafka2:29092,EXTERNAL://localhost:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka1:2181,2@kafka2:2181,3@kafka3:2181'

      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      BITNAMI_DEBUG: 'yes'
      KAFKA_CREATE_TOPICS: 'smartapi:5:3'
      
    volumes:
      - ./docker_data/kafka2:/bitnami/kafka
  kafka3:
    image: "bitnami/kafka:latest"
    container_name: kafka3
    ports:
      - 9094:9094
    environment:
      KAFKA_CFG_NODE_ID: 3
      KAFKA_BROKER_ID: 3
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_CFG_LISTENERS: 'INTERNAL://kafka3:29092,CONTROLLER://kafka3:2181,EXTERNAL://0.0.0.0:9094'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'INTERNAL://kafka2:29092,EXTERNAL://localhost:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka1:2181,2@kafka2:2181,3@kafka3:2181'

      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      BITNAMI_DEBUG: 'yes'
    volumes:
      - ./docker_data/kafka3:/bitnami/kafka