name: Quality Checks

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  # 1. Setup Stage: Create Conda environment and install dependencies
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      # Install Miniconda
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.12.3"
          activate-environment: app
          auto-update-conda: true

      # Cache the Conda environment
      - name: Cache Conda Environment
        uses: actions/cache@v3
        with:
          path: ~/conda/envs/app
          key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml', '**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      # Install Poetry and dependencies inside the Conda environment
      - name: Install Poetry and Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.8.2 -y
          source ~/conda/bin/activate app
          poetry install
        shell: bash -l {0} 

  # 2. Static Stage: Run static analysis without installing anything new
  static:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    
    needs: setup  # Ensure static job waits for setup to complete
    steps:
      - uses: actions/checkout@v3

      # Reuse the conda environment set up in the previous job
      - name: Activate Conda Environment
        run: |
          source ~/conda/bin/activate app
          

      # Perform static checks
      - name: black check
        run: black --diff --check $(git ls-files '*.py')

      - name: isort check
        run: isort --diff --check --profile black $(git ls-files '*.py')

      - name: mypy check
        run: mypy $(git ls-files '*.py')

      - name: pylint check
        run: pylint $(git ls-files '*.py')

  # 3. Test Stage: Run tests without installing anything new
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    needs: setup  # Ensure tests wait for setup to complete
    steps:
      - uses: actions/checkout@v3
      - name: Decode json credentials
        run: echo ${{ secrets.SMARTAPI_CREDENTIALS }} | jq > smartapi_credentials.json

     # Set up an environment variable with value "app"
      - name: Set up environment variable
        run: |
         echo "APP=app" >> $GITHUB_ENV
         echo "SMARTAPI_CREDENTIALS=smartapi_credentials.json" >>$GITHUB_ENV
      # Reuse the conda environment set up in the previous job
      - name: Reuse conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: app

      # Run pytest for tests
      - name: testing
        run: pytest tests/ -vv
