# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Market Data Api

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CONDA_ENV: "app"

permissions:
  contents: read

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Conda setup
      uses: conda-incubator/setup-miniconda@v2
      with: 
        activate-environment: "$CONDA_ENV"
        python-version: 3.10
    - name: activate environmet
      uses: conda activate "$CONDA_ENV"
    - name: conda package list
      run: conda list -n "$CONDA_ENV"
    
    - name: install poetry
      uses: Gr1N/setup-poetry@v8
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        poetry install
    - name: black check
      run: |
        which black
        black --version
    - name: static checks
      run:  |
        black --diff --check $(git ls-files '*.py')
        pylint $(git ls-files '*.py')
        mypy  $(git ls-files '*.py')
    - name: Test with pytest
      run: |
        pytest
