name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Or specify a specific version
          channel: 'stable'

      - run: flutter pub get
      - run: flutter analyze

      - name: Build Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter build linux --release
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-linux
          path: build/linux/x64/release/bundle