name: Flutter CI

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    # Step 1: Check out the code
    - uses: actions/checkout@v3

    # Step 2: Install Linux system dependencies
    - name: Install Linux system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libglib2.0-dev ninja-build cmake

    # Step 3: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    # Step 4: Get dependencies
    - name: Get dependencies
      run: flutter pub get

    # Step 5: Run Flutter analysis
    - name: Analyze
      run: flutter analyze

    # Step 6: Build Linux
    - name: Build Linux
      run: flutter build linux
